- .travis.yml
- Makefile
- main_test.go
- package.json
- shardmanager.go
This PR should fix https://github.com/mhchia/sharding-p2p-poc/issues/2, and the tests listed below
- `TestRouting`
- It seems the reason for it to fail is that dht queries fail. I ran the tests in `libp2p/go-libp2p-kad-dht` and found them failed as well. So further I tried `gx-go rw` to make the tests depend on versioned dependencies, and then the tests in `libp2p/go-libp2p-kad-dht` succeeded. Therefore, I tried it in our repo and it works, but for unknown reason.
- Just a note that the dht failed because of `dht: error writing message, trying again:  proto: invalid UTF-8 string dht_net.go:271`. It seems the proto data contained invalid UTF-8 in the field `Key`.
- Use gx to manage dependencies
- `TestPubSubNotifyListeningShards`
- Uncomment `n.PublishListeningShards`
> Fix failing tests

- cli-example/setup-3-partial-connecting-nodes.sh
- main.go
- main_test.go
- node.go
- shardmanager.go
Besides,
- Don't print blobs in collation to avoid unnecessary output.
- Fix `port` and `rpcport`, no matter what `seed` is used.
-  `port` and `rpcport` can be changed by specifying them when starting a node. To call RPC to the node, `rpcport` should be specified.
- Accordingly, `addpeer ip seed` is changed to `addpeer ip port seed`. The example usage can be found in `cli-example/setup-3-partial-connecting-nodes.sh`
> Add test for jumping shards

- README.md
The document URL in the readme is wrong
Replace it with the correct one
> Fix the wrong document URL

- addpeer.go
- main_test.go
- node.go
- requests.go
- rpcserver.go
- shardmanager.go
- Lack of test for `requestCollation` with `eventNotifier`
- One redundant step of `AddPeer`: `onResponse`
- Added the test for `requestCollation` with `eventNotifier`
- Remove the redundant step of `onResponse`
- Refactor `main_test.go` a little bit
> Add test for `requestCollation` with `eventNotifier`, and remove one redundant step of `AddPeer`

- addpeer.go
- cli-example/iterate_all_rpc_call.sh
- main.go
- node.go
- rpcserver.go
- shardmanager.go
[go-log](https://github.com/ipfs/go-log) is ipfs's library for logging which also supports APIs similar to opentracing's. The APIs are mainly wrappers over the original opentracing APIs(though not all of them) with some extra functionalities, see [doc](https://godoc.org/github.com/ipfs/go-log#example-EventLogger).
Differences between go-log and opentracing:
1. go-log generates spans from context object(e.g., `logger.Start(ctx, "span name")`) while in opentracing it's optional(opentracing supports `opentracing.StartSpan("span name", childOf(parentSpan)`, `opentracing.StartSpanFromConext(ctx, "span name", childOf(parentSpan))`)
- This makes it easier for go-log to pass along parent span.
- Though opentracing also supports injecting/extracting span into/from context object(e.g. …
> Try go-log and refactor error propagation

- bootstrap.go
- eventrpc.go
- main.go
- main_test.go
- requests.go
- rpcclient.go
- rpcserver.go
- script/partial-gx-uw.py
- shardmanager.go
- shardpreftable.go
- utils.go
- `Panic`, `Fatal`, `Error`, `Warning`, `Info`, `Debug`
- levels: `Critical`, `Error`, `Warning`, `Notice`, `Info`, `Debug`
- Default to?
`INFO`
https://c.pxhere.com/photos/25/ce/wild_animal_oregon_zoo_cub_feline_funny_play-521518.jpg!d)
> Replace builtin log with go log

- docker/dev.Dockerfile
Previous `dev.Dockerfile` doesn't run `go build` in `docker build`, which make it harder to test directly without running `go build` when start running the container.
Add `go build` in `dev.Dockerfile`, and run the executable when `docker run`.
> Run `go build` in docker build

- package.json
These dependencies are already transitively imported from `go-libp2p` or others.
> Remove unnecessary dependencies from package.json

- main.go
- package.json
Dep version of `go-floodsub`, `go-libp2p`, `go-libp2p-kad-dht` are stale. There were multiple fixes during these months in `go-floodsub`. We should make use of the fixes
Update it to the latest version, and also remove some unnecessary workaround which are no longer needed due to those fixes.
> Update deps' versions

- discovery.go
- main_test.go
- node.go
- rpcserver.go
- shardmanager.go
- shardpreftable.go
- shardpreftable_test.go
- `Advertise(ctx context.Context, shardID ShardIDType) error`
- advertise an already advertised shard => cancel the advertisement on that shard
- `FindPeers(ctx context.Context, shardID ShardIDType) ([]pstore.PeerInfo, error)`
> Abstract discovery

- deployment/ansible/.gitignore
- deployment/ansible/example_run_nodes.yml
- deployment/ansible/roles/common/tasks/cli_addpeer.yml
- deployment/ansible/scripts/topology.py
- deployment/terraform/example.tf
Two issue are fixed in this PR
- #81 security group is not specified.
- Since `topology.yml` is generated by a task, it can't be loaded as a global variable. The first run of the playbook would always fail and would work in the second run because `topology.yml` can be loaded then.
- Add security group in Terraform
- Don't load`topology.yml` as a global variable, use `include_vars` to load it once generated.
> Fix security group and topology loading

- main.go
`SIGSEGV` occurs when `tracer` is not `New`ed successfully and therefore `closer == nil`
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16135cd]
goroutine 1 [running]:
main.runServer(0x17d3d9d, 0x9, 0x2710, 0x0, 0x0, 0x0, 0x0, 0xc4200b3e10, 0xf, 0xc4200b3e30, ...)
/go/src/github.com/ethresearch/sharding-p2p-poc/main.go:160 +0x67d
main.main()
/go/src/github.com/ethresearch/sharding-p2p-poc/main.go:81 +0x5b0
```
Move `defer closer.Close()` to the `else` block
> Check `closer != nil` before `defer closer.Close()`

- eventrpc.go
- main.go
- main_test.go
- requests.go
- shardmanager.go
`eventnotifier` was set to `nil` if there was no event notifier server. However it was an interface with its value being `nil`, not a `nil` interface. So the comparison `n.eventnotifier != nil` will always return `true`.
Compare `n.eventnotifier` against typed `nil`
pic credit: [maxpixel](https://www.maxpixel.net/Cute-Kitty-Pets-Cat-1796843)
> Fix nil event notifier

- main.go
Tracer config takes in ENV variables `JAEGER_AGENT_HOST` and `JAEGER_AGENT_PORT` but it was presumed that these ENV variables will be passed in. And hence tracer will fail to initialize if the variables are not passed in.
Secondly, global tracer is set even if tracer fails to initialize.
> Fix nil tracer

- Makefile
I get an 'unable to find image' error when busting a make run-dev:
```
$ make run-dev
docker run -it --rm -v /Users/jonny/go/src/github.com/ethresearch/sharding-p2p-poc:/go/src/github.com/ethresearch/sharding-p2p-poc ethereum/sharding-p2p:dev sh -c "go build -v -o main ."
Unable to find image 'ethereum/sharding-p2p:dev' locally
docker: Error response from daemon: pull access denied for ethereum/sharding-p2p, repository does not exist or may require 'docker login'.
See 'docker run --help'.
make: *** [run-dev] Error 125
```
Fix the docker build command in the Makefile:
```
$ git diff Makefile 
diff --git a/Makefile b/Makefile
index 0e63774..21da292 100644
--- a/Makefile
+++ b/Makefile
@@ -11,7 +11,7 @@ build-prod:
docker build -f docker/prod.Dockerfile -t ethereum/sharding-p2p:latest . …
```
> resolves #102: modified the name of the image in the build-dev rule

- discovery.go
- docs/README.md
- main.go
- node.go
- package.json
- shardmanager.go
During solving #100 , an update of `go-libp2p-crypto` is needed.
Update `go-libp2p` along with `go-libp2p-kad-dht` and `go-libp2p-pubsub`.
**NOTE**: After updated `go-libp2p`, connecting peer keeps failing with error: `dial attempt failed: Failed to dial through 0 known relay hosts`.
And currently this is solved by disabling Relay when instantiating a libp2p host: `libp2p.New(…, libp2p.DisableRelay(), …)`. Should further investigate on how to use Relay.
> Update gx version

- main_test.go
- rpcserver.go
- shardmanager.go
- test/test_one_shard.py
- test/test_series.py
- test/utils.py
This PR includes the testing script `test/test_series.py`, which is capable of
- spinning up `n` docker nodes with `sharding-p2p-poc` running, connecting nodes, and broadcasting data
- measuring how much time it takes to receive a broadcasted data
- testing if the bootnodes functioning well
Also, added logs and fixes https://github.com/ethresearch/sharding-p2p-poc/issues/105 in `ShardManager`
```python
cd test
pip install python-dateutil
python test_series.py
```
- The script becomes slower when the number of nodes becomes larger, i.e. 100. Should find out the reason and solve it.
- The script uses threads when spinning up nodes and performing some CLIs, to reduce the time consumed. Probably need to change it when it consumes too many resources when the number of nodes becomes larger.
> Testing script for Whiteblock

- cli-example/common.sh
- cli-example/iterate_all_rpc_call.sh
- cli-example/setup-4-nodes.sh
- cli.go
- main.go
- node.go
- pb/rpc/rpc.pb.go
- pb/rpc/rpc.proto
- rpcserver.go
As described in https://github.com/ethresearch/sharding-p2p-poc/issues/108
bootstrap start
```bash
$ sharding-p2p-poc -client bootstrap start bootnodeStr1,bootnodeStr2,...
$ sharding-p2p-poc -rpcport=13002 -client bootstrap start `/ip4/127.0.0.1/tcp/10000/ipfs/QmS5QmciTXXnCUCyxud5eWFenUMAmvAWSDa1c7dvdXRMZ7,/ip4/127.0.0.1/tcp/10001/ipfs/QmexAnfpHrhMmAC5UNQVS8iBuUUgDrMbMY17Cck2gKrqeX`
```
bootstrap stop
```bash
$ sharding-p2p-poc -client bootstrap stop
```
> Add RPC `bootstrap`

- cli.go
- test/utils.py
The output from CLI `identify` is not in JSON format
Marshal it to JSON before printing
> JSON-ize the output from Identify

- test/test_series.py
- test/utils.py
> Fix bug that cmd_list is wrong quoted in `test/utils.py`, and add`test_issues`

- test/test_series.py
- test/utils.py
To align with the latest API in go
Besides, sleep 3 more seconds after `subshard` and print one more line in `test_reproduce_bootstrapping_issue`
> Fix the out-dated API subshard

- go.mod
- go.sum
1. jaeger-client-go@v.2.15.0 causes API breaks: https://github.com/jaegertracing/jaeger-client-go/issues/352#issuecomment-449347858
2. Fixes https://github.com/ethresearch/sharding-p2p-poc/issues/138: go 1.11.x < 1.11.4 generates wrong sums
1. Uses the older version
2. Regenerate the sum with later version: 1.11.4
> Update `go.sum` to use the sum from latest go, and downgrade jaeger-client
